#!/bin/bash 
cd "$(dirname "$(readlink -f "$0")" )"

:>aap.json 
[[ -d aap ]] && rm -rf aap
../aap init foobar -f
../aap install https://coderofsalvation@github.com/coderofsalvation/aap --save
grep -q "coderofsalvation/aap" aap.json || exit 1
exit 0
